//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMvspro
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassTable
    {
        public int Classid { get; set; }
        public string Section { get; set; }
        public string Teachername { get; set; }
        public Nullable<int> TotalStudents { get; set; }
    }
}
